### ISSUE TITLE
Not compatible with next 6?

### ISSUE THREAD

**Issue by shlomokraus** [saitonakamura/next-awesome-typescript#8]
Getting the following error when running the same example but with next 6.0.3":

Module build failed: Error: Plugin 0 specified in "base" provided an invalid property of "value"
    at Plugin.init (/Users/shlomokraus/Documents/projects/iqoqo-root/packages/app-web-user-dashboard/node_modules/babe
l-core/lib/transformation/plugin.js:131:13)
    at Function.normalisePlugin (/Users/shlomokraus/Documents/projects/iqoqo-root/packages/app-web-user-dashboard/node
_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
    at /Users/shlomokraus/Documents/projects/iqoqo-root/packages/app-web-user-dashboard/node_modules/babel-core/lib/tr
ansformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/shlomokraus/Documents/projects/iqoqo-root/packages/app-web-user-dashboard/nod
e_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/shlomokraus/Documents/projects/iqoqo-root/packages/app-web-user-dashboard/no
de_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/shlomokraus/Documents/projects/iqoqo-root/packages/app-web-user-dashboard/node_modul
es/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/shlomokraus/Documents/projects/iqoqo-root/packages/app-web-user-dashboard/node_modules
/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/shlomokraus/Documents/projects/iqoqo-root/packages/app-web-user-dashboard/node_modules/babel-c
ore/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/shlomokraus/Documents/projects/iqoqo-root/packages/app-web-user-dashboard/node_modul
es/babel-core/lib/transformation/pipeline.js:46:16)
    at /Users/shlomokraus/Documents/projects/iqoqo-root/node_modules/awesome-typescript-loader/src/index.ts:163:50
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by saitonakamura** [comment]
@shlomokraus as I'm looking on [next-typescript](https://github.com/zeit/next-plugins/commits/master/packages/next-typescript) package, it uses babel 7 which has [preset-typescript](https://new.babeljs.io/docs/en/next/babel-preset-typescript.html) with a first-class support for typescript transpilation.
I think it currently addresses most of the issues of `awesome-typescript-loader` vs `ts-loader` (cache), so I don't see the point of supporting it in next 6.

P.S. It's still has [some issues](https://new.babeljs.io/docs/en/next/babel-plugin-transform-typescript.html) though, but nothing critical from my perspective

**Comment by saitonakamura** [comment]
Closing it as no further activity
