### ISSUE TITLE
ModuleBuildError: Module build failed: ReferenceError: Unknown option: .dev.

### ISSUE THREAD

**Issue by etroynov** [saitonakamura/next-awesome-typescript#9]
Hi,

i have some problem:

```
 error  in ./pages/index.tsx

Module build failed: ReferenceError: Unknown option: .dev. Check out http://babeljs.io/docs/usage/options/ for more information about options.
    at buildUnknownError (/home/xxx/www/ti/packages/site/node_modules/@babel/core/lib/config/validation/options.js:98:11)
    at /home/xxx/www/ti/packages/site/node_modules/@babel/core/lib/config/validation/options.js:84:57
    at Array.forEach (<anonymous>)
    at validate (/home/xxx/www/ti/packages/site/node_modules/@babel/core/lib/config/validation/options.js:62:21)
    at loadPrivatePartialConfig (/home/xxx/www/ti/packages/site/node_modules/@babel/core/lib/config/partial.js:28:48)
    at loadFullConfig (/home/xxx/www/ti/packages/site/node_modules/@babel/core/lib/config/full.js:33:37)
    at transformSync (/home/xxx/www/ti/packages/site/node_modules/@babel/core/lib/transform-sync.js:13:36)
    at Object.transform (/home/xxx/www/ti/packages/site/node_modules/@babel/core/lib/transform.js:20:65)
    at /home/xxx/www/ti/packages/site/node_modules/awesome-typescript-loader/src/index.ts:163:50
    at process._tickCallback (internal/process/next_tick.js:68:7)

 @ multi ./pages/index.tsx
```

*package.json*

```
{
  "name": "site",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start-dev-site": "next",
    "start": "next start",
    "build": "next build"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "next": "^6.1.1",
    "react": "^16.4.1",
    "react-dom": "^16.4.1"
  },
  "devDependencies": {
    "@zeit/next-css": "^0.2.0",
    "next-awesome-typescript": "^0.3.2",
    "typescript": "^2.9.2"
  }
}
```

*tsconfig.json*

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "jsx": "preserve",
    "moduleResolution": "node",
    "sourceMap": false
  }
}
```

➜  site git:(master) ✗ node -v
v10.4.0

**Comment by saitonakamura** [comment]
@etroynov sorry for the late answer. This is strange, but this plugin isn't compatible with Next v6 [README.md This plugin only compatible with Next.js v5️](https://github.com/saitonakamura/next-awesome-typescript#%EF%B8%8F-this-plugin-only-compatible-with-nextjs-v5%EF%B8%8F-%EF%B8%8F) and I don't believe it'll be ([the reasoning behind](https://github.com/saitonakamura/next-awesome-typescript/issues/8#issuecomment-394487142)). The `npm` (`yarn`, whatever) should be warning you that your `next` dependency is incompatible with `next-awesome-typescript` `peerDependencies`, can you please check that on your side? Because if it doesn't I did something wrong, and it should and should be fixed.

**Comment by etroynov** [comment]
Ok, thank for answer
